### ISSUE TITLE
[Suggestion] Command permissions

### ISSUE THREAD

**Issue by Sternenforscher** [games647/LagMonitor#1]
Hello there,
i would find it useful if LagManager had an permission for each command, so we can control which informations users are able to see, and which not.
If you add this, i would recommend this very simple syntax: lagmanager.<command>

**Comment by games647** [comment]
You're right. Permissions are a must-have for this plugin. I added permissions for each command. You can see a list of all on the main page. Do you also need nested permissions? like:

[...].ping.playername
[...].graph.graphtype
...

**Comment by Sternenforscher** [comment]
I don't not know how others see this point, but for me, those permissions are fine as long commands don't have multiple functions which show very different informations.
For the ping command i would like to have an subpermission like lagmonitor.ping.other, but not necessarily.
