### ISSUE TITLE
The updater could not find any files for the project id 31279

### ISSUE THREAD

**Issue by Inysal** [games647/LagMonitor#12]
In the Console window I get this warning message:

[Thread-17/WARN]: [PermissionsEx] The updater could not find any files for the project id 31279

I would think it would be "Thread/Info" if there wasn't an update available like every other plugin I use.
I didn't know if there was an error or just a mislabel.

Thank you!

**Comment by games647** [comment]
That's a bug in curseforge (company behind devBukkit) mods api (http://wiki.bukkit.org/ServerMods_API).  It happens on auto updating when it tries to find a new update.
