### ISSUE TITLE
Spartan AntiCheat blocking socket connection

### ISSUE THREAD

**Issue by Twonox** [games647/LagMonitor#14]
> http://hastebin.com/nibufowewa.avrasm

Spartan is a Premium AntiCheat

**Comment by games647** [comment]
It's not an error. It shows you were the code is making this blocking connection. Http requests should be performed async and not on the main thread.

>Server is performing a blocking socket connection socket://johand.net:80 on the main thread

**Comment by games647** [comment]
It's inside the SideUtils.java file. Just report it to the author that he/she should do this async as the main thread is waiting for the response from the HTTP request and cannot perform other calculations on the main thread in the meanwhile.
