### ISSUE TITLE
Warn - [LagMonitor] Plugin unknown is performing a blocking action on the main thread This could be a performance hit.

### ISSUE THREAD

**Issue by Inysal** [games647/LagMonitor#17]
I have attached my nearly my entire console log below. I quite a few entries. 

 "[LagMonitor] Plugin unknown is performing a blocking action on the main thread This could be a performance hit." 

 LagMonitor can not detect the plugins, that may be a bug.

I was at a lost here, I don't know if it is something in LagMonitor doing this,
but at least it's showing.

All of my plugins are at the bottom of the pasted posted, on pastebin.

http://pastebin.com/CUKwRZCp

If there is anything I can do to help, or another place I need to go. I would be happy to, either way.

**Comment by games647** [comment]
Based on the stacktrace, I could already say it's:

SeePlayerInventory.VersionChecker
fastcraftplus.updater

I think based on the code location it's pretty much obvious what the plugins names and what these does in that moment. 

Weird that it doesn't detect the plugin names correctly. I'll look into it.

**Comment by games647** [comment]
At least now I have an example plugin where I can test it :D
