### ISSUE TITLE
Using securityMangerBlockingCheck on Windows Server

### ISSUE THREAD

**Issue by RoboMWM** [games647/LagMonitor#18]
...results in itself reporting itself as potentially causing lag, lol. Had to force close the server after this bout.

https://gist.github.com/RoboMWM/0204e2d0699831ac03a796fe01c8c98b

Edit: The initial messages (onEnable) also appears when set to false, but doesn't cause any spam afterwards

**Comment by games647** [comment]
The initial one is normal. That is debug code for someone who never replied to me afterwards :(

>...results in itself reporting itself as potentially causing lag, lol. Had to force close the server after this bout.

Sorry for that spam. I forgot that Java unloads and loads classes at runtime.
