### ISSUE TITLE
1.7.10?

### ISSUE THREAD

**Issue by Bysokar** [games647/LagMonitor#19]
Hi Man,
Just wondering if you have an older version of LagMonitor that supports 1.7.10 lying around?
Reason I ask is that hybrid servers are still stuck on 1.7 :( 
Regards,
Bysokar

**Comment by RoboMWM** [comment]
No https://github.com/games647/LagMonitor/issues/16

**Comment by RoboMWM** [comment]
Also, if you're on 1.7... good luck on getting any support regardless of LagMonitor. You're out on your own there for the most part, you're basically running Windows XP.

**Comment by Bysokar** [comment]
**Most** modded servers run 1.7, as it is able to support bother plugins and mods. Sponge is about a year from being able to take that on (it is missing support for basic stuff in its API like WorldEdit last time I checked).

**Comment by RoboMWM** [comment]
Well if you're running cauldron, LagMonitor, afaik, is only going to be able to monitor the bukkit side of that. (And afaik bukkit + forge mods/whatever never played well together anyhow)

**Comment by Bysokar** [comment]
Massivelag handles the forge and bukkit sides (even though the author thinks it will only handle the bukkit side of it)

**Comment by RoboMWM** [comment]
Ok, then that means forge stuff is integrated into the bukkit tick loop or whatever. Which I can only imagine how many issues/fun debugging that might cause depending on how deep a bukkit plugin might dig into the server.

**Comment by Bysokar** [comment]
Its the same as digging into the bukkit tick loop.... you find the code section and rectify the issue.

**Comment by Bysokar** [comment]
Your (rather blunt) response has made me look into Sponge development, to port our custom plugins across. Thanks ;)
