### ISSUE TITLE
Suggestion: /lagmonitor (help)

### ISSUE THREAD

**Issue by BiGUNMAN** [games647/LagMonitor#20]
It would be really useful if a  /lagmonitor command existed. It would display the list of lag monitor commands, so that one wouldn't need to remember or reference the plugin page for them.

Combining them into /lagmonitor heap/monitor/etc, would be nice addition too.

**Comment by games647** [comment]
Can't you use 
>/? LagMonitor ? 

That should print the commands with their usage and description.

**Comment by BiGUNMAN** [comment]
Considering you need to give a user the following permission makes that
command quite inconvenient. http://i.imgur.com/AfujftU.png

**Comment by BiGUNMAN** [comment]
No all the commands are displayed. Here's a snapshot: http://i.imgur.com/0oMHE7m.png

Look at the /<command> inputs.
