### ISSUE TITLE
This could be a performance hit. (Warned)

### ISSUE THREAD

**Issue by M9GLiquid** [games647/LagMonitor#25]
`
09.02 20:13:17 [Server] WARN Plugin Unknown is performing a blocking action to socket://api.mojang.com:443 on the main thread This could be a performance hit. Such actions should be handled async from the main thread Report it to the plugin author
09.02 20:13:17 [Server] WARN The following exception is not an error. It's a hint for the plugin developer to find the source of the blocking action. LagMonitor doesn't prevent this action. It just warns you
09.02 20:13:17 [Server] INFO java.lang.Exception
09.02 20:13:17 [Server] INFO at com.github.games647.lagmonitor.listeners.BlockingConnectionSelector.select(BlockingConnectionSelector.java:40) [LagMonitor.jar:?]
09.02 20:13:17 [Server] INFO at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:384) [?:1.8.0_121]
09.02 20:13:17 [Server] INFO at java.net.Socket.connect(Socket.java:589) [?:1.8.0_121]
09.02 20:13:17 [Server] INFO at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668) [?:1.8.0_121]
09.02 20:13:17 [Server] INFO at sun.net.NetworkClient.doConnect(NetworkClient.java:175) [?:1.8.0_121]
09.02 20:13:17 [Server] INFO at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) [?:1.8.0_121]
09.02 20:13:17 [Server] INFO at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) [?:1.8.0_121]
09.02 20:13:17 [Server] INFO at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) [?:1.8.0_121]
09.02 20:13:17 [Server] INFO at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) [?:1.8.0_121]
09.02 20:13:17 [Server] INFO at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) [?:1.8.0_121]
09.02 20:13:17 [Server] INFO at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181) [?:1.8.0_121]
09.02 20:13:17 [Server] INFO at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032) [?:1.8.0_121]
09.02 20:13:17 [Server] INFO at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) [?:1.8.0_121]
09.02 20:13:17 [Server] INFO at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316) [?:1.8.0_121]
09.02 20:13:17 [Server] INFO at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291) [?:1.8.0_121]
09.02 20:13:17 [Server] INFO at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250) [?:1.8.0_121]
09.02 20:13:17 [Server] INFO at com.mojang.authlib.HttpAuthenticationService.performPostRequest(HttpAuthenticationService.java:77) [spigot83.jar:git-Spigot-b32c8f8-4d3bf20]
09.02 20:13:17 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:66) [spigot83.jar:git-Spigot-b32c8f8-4d3bf20]
09.02 20:13:17 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:54) [spigot83.jar:git-Spigot-b32c8f8-4d3bf20]
09.02 20:13:17 [Server] INFO at net.minecraft.server.v1_11_R1.UserCache.a(UserCache.java:88) [spigot83.jar:git-Spigot-b32c8f8-4d3bf20]
09.02 20:13:17 [Server] INFO at net.minecraft.server.v1_11_R1.UserCache.getProfile(UserCache.java:157) [spigot83.jar:git-Spigot-b32c8f8-4d3bf20]
09.02 20:13:17 [Server] INFO at net.minecraft.server.v1_11_R1.CommandOp.execute(SourceFile:38) [spigot83.jar:git-Spigot-b32c8f8-4d3bf20]
09.02 20:13:17 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.command.VanillaCommandWrapper.dispatchVanillaCommand(VanillaCommandWrapper.java:109) [spigot83.jar:git-Spigot-b32c8f8-4d3bf20]
09.02 20:13:17 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:38) [spigot83.jar:git-Spigot-b32c8f8-4d3bf20]
09.02 20:13:17 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot83.jar:git-Spigot-b32c8f8-4d3bf20]
09.02 20:13:17 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) [spigot83.jar:git-Spigot-b32c8f8-4d3bf20]
09.02 20:13:17 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:636) [spigot83.jar:git-Spigot-b32c8f8-4d3bf20]
09.02 20:13:17 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:437) [spigot83.jar:git-Spigot-b32c8f8-4d3bf20]
09.02 20:13:17 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot83.jar:git-Spigot-b32c8f8-4d3bf20]
09.02 20:13:17 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot83.jar:git-Spigot-b32c8f8-4d3bf20]
09.02 20:13:17 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot83.jar:git-Spigot-b32c8f8-4d3bf20]`

**Comment by games647** [comment]
The op command made a blocking server connection to Mojang.
