### ISSUE TITLE
Merge permission

### ISSUE THREAD

**Issue by PiggyPiglet** [games647/LagMonitor#26]
Hi, can I merge this plugin with 2 other plugins? I have a plugin that allows me to clear unused ram and the other plugin monitors ram and sends it to my server panel for a more accurate ram usage graph.

**Comment by games647** [comment]
https://github.com/games647/LagMonitor/blob/master/LICENSE

> to deal
in the Software without restriction, including without limitation the rights
to use, **copy, modify, merge**, publish, distribute, sublicense
