### ISSUE TITLE
LagMonitor error

### ISSUE THREAD

**Issue by DanielTravi** [games647/LagMonitor#30]
Travisuniverse is the file spigot-1.11.2
Error:
08.05 21:38:49 [Server] WARN [LagMonitor] Plugin LagMonitor is performing a threading action on the main thread This could be a performance hit Socket: socket://fof1092.de:443. Such actions should be handled async from the main threadReport it to the plugin author
08.05 21:38:49 [Server] WARN [LagMonitor] The following exception is not an error. It's a hint for the plugin developer to find the source of the threading action. LagMonitor doesn't prevent this action. It just warns you
08.05 21:38:49 [Server] INFO java.lang.IllegalAccessException
08.05 21:38:49 [Server] INFO at com.github.games647.lagmonitor.threading.BlockingActionManager.logCurrentStack(BlockingActionManager.java:39) [LagMonitor.jar:?]
08.05 21:38:49 [Server] INFO at com.github.games647.lagmonitor.threading.BlockingActionManager.checkBlockingAction(BlockingActionManager.java:26) [LagMonitor.jar:?]
08.05 21:38:49 [Server] INFO at com.github.games647.lagmonitor.listeners.BlockingConnectionSelector.select(BlockingConnectionSelector.java:27) [LagMonitor.jar:?]
08.05 21:38:49 [Server] INFO at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:384) [?:1.8.0_111]
08.05 21:38:49 [Server] INFO at java.net.Socket.connect(Socket.java:589) [?:1.8.0_111]
08.05 21:38:49 [Server] INFO at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668) [?:1.8.0_111]
08.05 21:38:49 [Server] INFO at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173) [?:1.8.0_111]
08.05 21:38:49 [Server] INFO at sun.net.NetworkClient.doConnect(NetworkClient.java:180) [?:1.8.0_111]
08.05 21:38:49 [Server] INFO at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) [?:1.8.0_111]
08.05 21:38:49 [Server] INFO at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) [?:1.8.0_111]
08.05 21:38:49 [Server] INFO at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) [?:1.8.0_111]
08.05 21:38:49 [Server] INFO at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) [?:1.8.0_111]
08.05 21:38:49 [Server] INFO at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) [?:1.8.0_111]
08.05 21:38:49 [Server] INFO at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138) [?:1.8.0_111]
08.05 21:38:49 [Server] INFO at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032) [?:1.8.0_111]
08.05 21:38:49 [Server] INFO at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) [?:1.8.0_111]
08.05 21:38:49 [Server] INFO at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546) [?:1.8.0_111]
08.05 21:38:49 [Server] INFO at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) [?:1.8.0_111]
08.05 21:38:49 [Server] INFO at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) [?:1.8.0_111]
08.05 21:38:49 [Server] INFO at me.F_o_F_1092.PayForCommand.PluginManager.UpdateListener$1.run(UpdateListener.java:81) [PayForCommands%20MC1.9-1.11.jar:?]
08.05 21:38:49 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) [TravisUniverse.jar:git-Spigot-38ddb34-c19c293]
08.05 21:38:50 [Multicraft] Skipped 58 lines due to rate limit (30/s)
08.05 21:38:50 [Server] INFO [HyperDrive] Your current HyperDrive version does not match the latest version. You might want to warp your way back to that spigot page and update! ;)

**Comment by games647** [comment]
Sorry. I sent it from mobile. It's pay for command. Next time just comment again in the old ticket.

**Comment by DanielTravi** [comment]
Thanks
