### ISSUE TITLE
possibility for async threading?

### ISSUE THREAD

**Issue by xXxBobDolexXx** [games647/LagMonitor#31]
When using the plugin, my console provides the following message

Just wondering if theres any plans to include async in the plugin
https://hastebin.com/ajovegumor.swift

**Comment by games647** [comment]
It's not an issue of LagMonitor. It's actually AntiSwear. So the message should be:

>Plugin AntiSwear is performing a threading...

LagMonitor just detects that there is blocking connection and provide you as admin this message to fix it (like messaging the plugin developer) in order to provide a better performance.
