### ISSUE TITLE
No download on the ci?

### ISSUE THREAD

**Issue by PiggyPiglet** [games647/LagMonitor#36]
Sorry if this is a stupid question, but I honestly can't find any sort of download button on the latest build, at travis ci. https://travis-ci.org/games647/LagMonitor. Am I missing something, or do I have to compile it myself?

**Comment by games647** [comment]
Travis is only used for checking if unit tests pass and the project still compiles on an independent platform. You could download the latest build from here: https://ci.codemc.org/job/LagMonitor/
