### ISSUE TITLE
Heap Command

### ISSUE THREAD

**Issue by ryanwoods1706** [games647/LagMonitor#38]
It seems to be outputting this:
https://prntscr.com/iuixwi

In the #1 and #2 spots its not showing me the class name

**Comment by games647** [comment]
Actually that is the class name. `[B` stands for byte array and `[C` stands for char array. Those values are primitives inside an array. Primitives are encoded with

| Type        | Encoded           | 
| ------------- |:-------------:| 
| boolean | Z |
| byte | B |
| char | C |
| short | S |
| int | I |
| long | J |
| float | F |
| double | D |
| primtivie type in array | [name |
| non-primitive type in array | [Lclass |
