### ISSUE TITLE
NoClassDefFoundError /WinNT$HANDLEByReference

### ISSUE THREAD

**Issue by ItsMennyo** [games647/LagMonitor#39]
Hey! I get this error with the latest dev build: https://hastebin.com/wubibuluri.sql Tnxx.

**Comment by games647** [comment]
Do you use Oracle Java? Do you have JRE or JDK (Development Kit) installed?

**Comment by ItsMennyo** [comment]
I think so. This is all what I have form Oracle: https://gyazo.com/f075f32ced4221967e5f31c9e0b1b0c0

**Comment by games647** [comment]
Could you run the newer build?

**Comment by ItsMennyo** [comment]
I now get this error: https://hastebin.com/yudozijako.swift

**Comment by games647** [comment]
I think the maven-shade plugin remove something too much. One try again, please.

**Comment by ItsMennyo** [comment]
I still get the same error...

**Comment by games647** [comment]
Can I get the complete log? I guess it's failing to extract the native ddl.

**Comment by ItsMennyo** [comment]
Complete log of the error or full console?

**Comment by games647** [comment]
Complete server log.

**Comment by ItsMennyo** [comment]
https://hastebin.com/bobicecuxo.md

**Comment by games647** [comment]
Okay it was the relocation process. Let's try now if the first error is fixed.

**Comment by ItsMennyo** [comment]
Everything works now. It don't give an error and the config is generated.

**Comment by ItsMennyo** [comment]
I now only have a error with the /timing command ingame: https://hastebin.com/igicegizeh.vbs

**Comment by games647** [comment]
You're using Paper, so you should use the paper command for that.

**Comment by ItsMennyo** [comment]
Hmm. Okay tnxx.
