### ISSUE TITLE
Add PaperSpigot support for timings

### ISSUE THREAD

**Issue by NoChanceSD** [games647/LagMonitor#5]
Got this error executing /timing command.
Also i'm using PaperSpigot.
http://pastebin.com/7ie1NqwY

**Comment by games647** [comment]
Oh right. PaperSpigot uses a new timings system (called v2). It's very complex, but I'll add support for it.

**Comment by NoChanceSD** [comment]
Thanks.
Btw, v2 is also far from being ready and useful in my opinion so you could just give a "Not supported" message or something.

**Comment by games647** [comment]
Although it's very complex, I think it can be pretty useful for various reasons. First it includes more data like the player ping average, memory usage for each minute, .... Moreover you can get more detailed information of your server by having a history which you can scroll through.
