### ISSUE TITLE
Ping the real ip when connected via a bungee server

### ISSUE THREAD

**Issue by sgdc3** [games647/LagMonitor#6]

**Comment by games647** [comment]
It should already use the ping of the real player, because BungeeCord is just forwarding the packets.

**Comment by sgdc3** [comment]
No, all the packets have the bungee server's address as surce.
The ip_foward feature only hooks into a spigot hook that ovverrides the getAddress() method.

**Comment by games647** [comment]
Yes, but the ping command in LagMonitor uses the Minecraft ping (Keep alive packet) not the OS-ping (ICMP).

**Comment by sgdc3** [comment]
Yeah, i know, but yesterday i tryed and everyone has 0ms as ping. (Using Waterfall as bungee proxy)

**Comment by games647** [comment]
I'll check it.

**Comment by games647** [comment]
Which version do you use?

**Comment by sgdc3** [comment]
ok, i'll try with latest version from jenkins

**Comment by games647** [comment]
Any updates on this?

**Comment by sgdc3** [comment]
Idk xD I install the plugin only when i need to fix lag issues.

**Comment by sgdc3** [comment]
It works now, thanks
