### ISSUE TITLE
1.15 Graphs don't work

### ISSUE THREAD

**Issue by marvinej** [games647/LagMonitor#60]
it just puts a regular unrevealed map in your hand.

**Comment by games647** [comment]
Do you tried a development build from here: https://ci.codemc.io/job/Games647/ ?

**Comment by sgdc3** [comment]
I can confirm that the latest dev build doesn't work

**Comment by games647** [comment]
@sgdc3 You tried it on Minecraft 1.15?

**Comment by marvinej** [comment]
For me its on paper 1.15.2

**Comment by games647** [comment]
Okay that's weird. I just tried it and it worked for me. Do you use the default graph command?

**Comment by marvinej** [comment]
it appears to be working for me on the build i downloaded


------
Respectfully,
Eli Marvin

**Comment by ITCMD** [comment]
Also not working for me on 1.15.2

**Comment by ITCMD** [comment]
I hadn't realized that the above comment was stating that he had downloaded the linked build. Downloading a later build did solve the issue.
