### ISSUE TITLE
Cannot find com.destroystokyo.paper.PaperConfig

### ISSUE THREAD

**Issue by Inysal** [games647/LagMonitor#8]
Error Details at:   http://pastebin.com/CL1u4UFv

Versions:
  git-Spigot-e6f93f4-935f18b (MC: 1.9.2)
  1.9.2-R0.1-SNAPSHOT
  Java 1.8.0_60
  LagMonitor 1.3
  FastCraft+ v0.20.1
  bChatManager 3.1.2
  ChatColor2 1.6.8
  ClearLag 2.9.1
  CoreProtect 2.12.0
  CustomEnderChest 1.1.1
  iConomy_Recreation 8.0
  LockettePro 2.1.3
  Orebfuscator4 4.0.9-SNAPSHOT
  PermissionsEx 1.23.4
  RPGMobMoney 1.3.1
  SeePlayerInventory 1.7
  SignEdit 3.3.2
  SignShop 2.11.0
  SimpleHomes 2.0.3
  SimpleSort 1.4
  StarterKit 1.3.7-SNAPSHOT
  SurvivalFly 1.0
  TreeAssist 5.10.1
  UberEnchant 3.1
  Vault 1.5.6-b49
  Vote 1.903
===========================================

**Comment by games647** [comment]
Thank you for the report
